/**
 * dsh-request-log — Client half (installed package bundle entry).
 *
 * Registers a "Requests / 请求" tab in the conversation view ring
 * (`conversation.view` slot, right of Chat/Trajectory/Context) listing every
 * recorded provider call of the open session; each row drills into the exact
 * request and response, viewable in the neutral capture or rendered into the
 * Anthropic Messages / OpenAI ChatCompletion / OpenAI Responses wire shapes.
 *
 * Data comes from the Host half's same-origin read API — no RPC, no
 * projections: plain fetch against `/dsh-request-log/*`.
 */

import './styles.css'

import { h } from './react'
import type { ClientCtx } from './services'
import type { ViewDict } from './dict'
import { makeRequestLogView } from './view'


const NS = 'dsh-request-log'

const DICT_EN: ViewDict = {
  tab: 'Requests',
  empty: 'No provider calls recorded yet',
  emptyHint: 'Send a message in this session — every model call (retries included) will be listed here.',
  error: 'Failed to load',
  retry: 'Retry',
  stepHint: 'Step of this session\'s conversation loop — attempt 1 opens a step, retries share it; auxiliary calls (compaction / title) take none',
  stale: 'Last refresh failed — showing previously loaded data',
  refresh: 'Refresh',
  refreshHint: 'Reload the whole loaded window now. Auto only fetches the newest calls, so this is the way to re-sync after a failed refresh, or while Auto is off.',
  auto: 'Auto',
  autoHint: 'Auto-refresh: check for new calls every 3s. Paused while this tab is in the background or a call detail is open. Following the newest row is separate and always on — the ledger tracks the bottom whenever you are already there.',
  time: 'Time',
  model: 'Model',
  ttft: 'TTFT',
  totalTime: 'Total',
  colSpeed: 'Speed',
  speedHint: 'Output tokens per second over the response stream (TTFT excluded)',
  colBilledInput: 'Total in',
  colIn: 'In',
  colCacheRead: 'Cache hit',
  hitRateHint: 'Cache hit rate',
  colHitRate: 'Hit %',
  colCacheWrite: 'Cache write',
  colOut: 'Out',
  colReasoning: 'Reasoning',
  colAnswer: 'Answer',
  size: 'Msg/Calls',
  sizeHint: 'Messages in the request / tool calls made by the response — a run_code program counts its inner dispatch sites',
  retryOf: 'Retry attempt of the same logical call',
  sumCalls: 'Calls',
  sumCallsOf: 'of {total} calls',
  sumFailed: 'Failed',
  sumFailedHint: '{errors} errors · {aborts} aborted',
  sumRetried: 'Retried',
  sumRetriedHint: 'Attempts that re-sent a previous request',
  sumBilledInput: 'Total in',
  sumBilledInputHint: 'Billed input over the loaded calls: uncached input + cache hits + cache writes',
  sumStorage: 'Disk added',
  sumStorageHint: 'What this session ADDED to the store: {envelope} of envelope lines + {objects} of compressed objects — {pct} of the {cap} per-session cap. Marginal, not the transcript’s weight: a piece already stored bills nothing, so a retry adds 0 and pieces two sessions share bill to whichever wrote them first. Per-session figures never sum to the store directory.',
  sumInput: 'Input',
  sumUncached: 'uncached',
  sumCached: 'cached',
  sumWritten: 'written',
  sumHitRate: 'Hit rate',
  sumCacheWrite: 'Cache write',
  sumOutput: 'Output',
  loadMore: 'Load older ({count} more)',
  backToTop: 'Back to top',
  toLatest: 'Jump to the latest call',
  charts: {
    toggle: 'Charts',
    toggleHint: 'Per-call line charts over the loaded window',
    groupHitRate: 'Hit rate',
    groupTokens: 'Tokens',
    groupLatency: 'Latency',
    groupSpeed: 'Speed',
    stacks: 'Stacked',
    stacksHint: 'Stack the token series on top of each other, per step',
    cumulative: 'Cumulative',
    cumulativeHint: 'Running totals: on the step axis, stacked bars whose column tops at the cumulative usage up to that step (like the Cursor usage dashboard); on the time axis, the same totals as a stacked area. Color segments break it down by token kind',
    xAxisToStep: 'By step',
    xAxisToTime: 'By time',
    xAxisHint: 'Switch the x axis. By time places each call at its wall clock, so a burst clusters and an idle hour is a visible gap, and compaction / title calls join the chart. By step gives every conversation turn equal width and numbers it #1, #2, …, collapsing retries into the step they retry',
    emptyTitle: 'Nothing to plot yet',
    emptyHint: 'Statistics appear once calls settle with usage in this session.',
    allNull: 'This metric was never reported for the loaded calls.',
    speedApproxHint: '≈ value = output ÷ total duration — this response flushed at once (no measurable stream phase), so TTFT is included.',
    excludedShort: '{count} aux',
    excludedHint: '{count} auxiliary calls (compaction / session-title) are not on the numbered step axis.',
  },
  detail: {
    back: 'Back',
    step: 'Step',
    timingCard: 'Timing',
    startedAt: 'Started',
    waitPhase: 'Request wait',
    waitHint: 'From call start to the first chunk from the provider (time to first token)',
    streamPhase: 'Response stream',
    streamHint: 'From the first chunk to the last chunk of the stream',
    totalPhase: 'Total',
    usageCard: 'Token usage',
    usageNone: 'No usage reported for this call',
    input: 'Input (uncached)',
    cacheRead: 'Cache hit',
    cacheWrite: 'Cache write',
    output: 'Output',
    reasoning: 'Reasoning',
    hitRate: 'Hit rate',
    billedInput: 'Total in',
    outSpeed: 'Output speed',
    outSpeedHint: 'Output tokens ÷ response stream duration (TTFT excluded)',
    callCard: 'Call',
    provider: 'Provider',
    model: 'Model',
    effort: 'Effort',
    attempt: 'Attempt · hash',
    retryOf: 'Retry attempt of the same logical call',
    finish: 'Finish',
    size: 'Size',
    msgs: 'msgs',
    callsLabel: 'tool calls',
    callsHint: 'Tool calls made by this response; a run_code program counts its inner tools.x(...) dispatch sites',
    request: 'Request',
    response: 'Response',
    neutral: 'Neutral',
    reconstructed: 'Reconstructed view: rendered from the exact neutral capture, mirroring the adapter mapping',
    expandAll: 'Expand',
    expandHint: 'Expand every node and string',
    collapseAll: 'Collapse',
    collapseHint: 'Collapse every node and clamp long strings',
    chainOn: 'Chain view: {sent} new items · a chaining client could reuse previous_response_id ({skipped} items already sent with the prior request — the full input is still recorded here)',
    chainOff: 'Full input: the whole history travels in this request ({items} items)',
    copy: 'Copy JSON',
    copied: 'Copied',
    copyFailed: 'Copy failed',
    loadError: 'Failed to load call',
    jsonCollapse: 'collapse',
    jsonExpand: 'expand',
    jsonChars: '{count} chars',
    jsonViewAsJson: 'view as JSON',
    jsonViewAsText: 'view text',
    jsonViewAsJsonTitle: 'Parse this string and show it as JSON',
    jsonViewAsTextTitle: 'Show this string as plain text',
    jsonCollapseStringTitle: 'Collapse this string back to its preview',
    jsonOpenString: '… +{count} chars',
    jsonOpenStringTitle: 'Open this string in full',
    jsonChip: '{ } JSON',
    jsonTruncated: '… truncated at {count} chars — use Copy JSON for the full body',
    jsonItems: '{count} items',
    jsonKeys: '{count} keys',
    jsonNodeBudget: '… node budget exceeded, collapse other nodes or use Copy JSON ',
    jsonDepthBudget: '… depth limit ({count} levels) reached — use Copy JSON for the full body',
    renderError: 'Rendering failed',
    renderRetry: 'Retry',
  },
}

const DICT_ZH: ViewDict = {
  tab: '请求',
  empty: '尚未记录到任何模型调用',
  emptyHint: '在本会话发送一条消息 —— 每次模型调用（含重试）都会列在这里。',
  error: '加载失败',
  retry: '重试',
  stepHint: '本会话对话循环的步骤序号 —— 每次新调用开启一步，重试沿用其所属步骤；辅助调用（压缩 / 标题）不占步骤',
  stale: '上次刷新失败 —— 当前展示的是已加载的数据',
  refresh: '刷新',
  refreshHint: '立即重载整个已加载窗口。自动刷新只拉最新的若干条，所以刷新失败之后、或关掉自动刷新时，靠它重新同步。',
  auto: '自动',
  autoHint: '自动刷新：每 3 秒检查一次新调用。标签页切到后台、或打开了某次调用的详情时暂停。跟随最新一行是另一回事，且一直开着——只要你本来就在底部，台账就会跟着走。',
  time: '时间',
  model: '模型',
  ttft: '首字延迟',
  totalTime: '总时长',
  colSpeed: '速度',
  speedHint: '响应流式阶段的输出 token 速度（不含首字延迟）',
  colBilledInput: '总输入',
  colIn: '输入',
  colCacheRead: '缓存命中',
  hitRateHint: '缓存命中率',
  colHitRate: '命中率',
  colCacheWrite: '缓存写入',
  colOut: '输出',
  colReasoning: '思考',
  colAnswer: '回答',
  size: '消息/调用',
  sizeHint: '请求消息数 / 响应发起的工具调用次数 —— run_code 程序按其内部调用点计数',
  retryOf: '同一逻辑调用的重试尝试',
  sumCalls: '调用数',
  sumCallsOf: '共 {total} 次',
  sumFailed: '失败',
  sumFailedHint: '{errors} 次错误 · {aborts} 次中止',
  sumRetried: '重试',
  sumRetriedHint: '重发同一请求的尝试次数',
  sumBilledInput: '总输入',
  sumBilledInputHint: '已加载调用的计费输入合计：未缓存输入 + 缓存命中 + 缓存写入',
  sumStorage: '新增占用',
  sumStorageHint: '本会话向存储「新增」的量：信封行 {envelope} + 压缩对象 {objects} —— 占单会话上限 {cap} 的 {pct}。这是增量，不是对话内容的重量：已存在的分片不计费，所以重试记 0，两个会话共享的分片算在先写入的那一方。各会话的数字加起来不等于存储目录的大小。',
  sumInput: '输入',
  sumUncached: '未缓存',
  sumCached: '已缓存',
  sumWritten: '写入',
  sumHitRate: '命中率',
  sumCacheWrite: '缓存写入',
  sumOutput: '输出',
  loadMore: '加载更早的调用（还有 {count} 条）',
  backToTop: '回到顶部',
  toLatest: '跳到最新调用',
  charts: {
    toggle: '图表',
    toggleHint: '按已加载调用的逐次折线统计图',
    groupHitRate: '命中率',
    groupTokens: 'Token',
    groupLatency: '延迟',
    groupSpeed: '速度',
    stacks: '堆叠',
    stacksHint: '将 Token 各序列在同一步骤上依次堆叠显示',
    cumulative: '累计',
    cumulativeHint: '累计用量：步骤轴上是堆叠柱状图，每根柱子的高度为截至该步骤的累计用量（类似 Cursor 用量看板）；时间轴上同样的累计值画成堆叠面积图。各色段为各类 token 的累计构成',
    xAxisToStep: '按步骤',
    xAxisToTime: '按时间',
    xAxisHint: '切换横坐标。按时间：每次调用落在它真实发生的时刻，密集请求会挤在一起、空闲一小时就是一段看得见的空白，压缩与起标题等辅助调用也会一并画出。按步骤：每个对话回合等宽并编号 #1、#2……，重试并入它所重试的那一步',
    emptyTitle: '暂无可绘制的数据',
    emptyHint: '本会话的调用完成并报告用量后，这里会出现统计折线。',
    allNull: '已加载的调用从未报告该指标。',
    speedApproxHint: '≈ 数值 = 输出 ÷ 总时长 —— 该响应一次性返回（无可测流式阶段），已计入首字等待。',
    excludedShort: '{count} 辅助',
    excludedHint: '{count} 个辅助调用（压缩 / 标题）不在编号步骤轴上，未计入折线。',
  },
  detail: {
    back: '返回',
    step: '步骤',
    timingCard: '耗时',
    startedAt: '开始时间',
    waitPhase: '请求等待',
    waitHint: '从调用开始到 Provider 返回第一个数据块（首 token 延迟）',
    streamPhase: '响应流式',
    streamHint: '从第一个数据块到最后一个数据块的流式传输时长',
    totalPhase: '总时长',
    usageCard: 'Token 用量',
    usageNone: '本次调用未报告用量',
    input: '输入（未缓存）',
    cacheRead: '缓存命中',
    cacheWrite: '缓存写入',
    output: '输出',
    reasoning: '思考',
    hitRate: '命中率',
    billedInput: '总输入',
    outSpeed: '输出速度',
    outSpeedHint: '输出 token ÷ 响应流式时长（不含首字延迟）',
    callCard: '调用信息',
    provider: '提供方',
    model: '模型',
    effort: '思考强度',
    attempt: '尝试 · 哈希',
    retryOf: '同一逻辑调用的重试尝试',
    finish: '结束原因',
    size: '规模',
    msgs: '条消息',
    callsLabel: '次工具调用',
    callsHint: '本次响应发起的工具调用次数；run_code 程序按其内部 tools.x(...) 调用点计数',
    request: '请求',
    response: '响应',
    neutral: '中立格式',
    reconstructed: '重建视图：基于精确的中立格式记录渲染，映射规则与适配器一致',
    expandAll: '展开',
    expandHint: '展开全部节点和字符串',
    collapseAll: '折叠',
    collapseHint: '折叠全部节点并收起长字符串',
    chainOn: '链式视图：{sent} 条新增内容 · 链式客户端可复用 previous_response_id（{skipped} 条已随前次请求发送——完整输入仍记录于本条）',
    chainOff: '全量输入：完整历史随本次请求发送（{items} 条）',
    copy: '复制 JSON',
    copied: '已复制',
    copyFailed: '复制失败',
    loadError: '加载调用记录失败',
    jsonCollapse: '收起',
    jsonExpand: '展开',
    jsonChars: '{count} 字符',
    jsonViewAsJson: '按 JSON 查看',
    jsonViewAsText: '查看文本',
    jsonViewAsJsonTitle: '解析该字符串并按 JSON 显示',
    jsonViewAsTextTitle: '将该字符串按纯文本显示',
    jsonCollapseStringTitle: '收起该字符串，回到预览',
    jsonOpenString: '… +{count} 字符',
    jsonOpenStringTitle: '完整展开该字符串',
    jsonChip: '{ } JSON',
    jsonTruncated: '… 已在 {count} 字符处截断 — 完整内容请使用“复制 JSON”',
    jsonItems: '{count} 项',
    jsonKeys: '{count} 个键',
    jsonNodeBudget: '… 渲染节点数超限，请折叠其他节点或使用“复制 JSON”',
    jsonDepthBudget: '… 嵌套深度已达上限（{count} 层）— 完整内容请使用“复制 JSON”',
    renderError: '渲染失败',
    renderRetry: '重试',
  },
}

function apply(ctx: ClientCtx): void {
  const dicts: Record<string, ViewDict> = { en: DICT_EN, zh: DICT_ZH }

  ctx.effect(() => {
    return ctx.locale.register(NS, { en: DICT_EN, zh: DICT_ZH })
  }, 'dsh-request-log: dictionaries')
  const t = ctx.locale.bind(NS)

  const source = {
    dictOf: (): ViewDict => {
      const active = ctx.locale.getLocale?.().active ?? 'en'
      return dicts[active] ?? DICT_EN
    },
    subscribe: (fn: () => void): (() => void) => ctx.locale.subscribe(fn),
  }
  const RequestLogView = makeRequestLogView(source)

  ctx.slots.inject('conversation.view', () => {
    return ctx.slots.register(
      // order 30 renders right of Chat (0), Trajectory (10), and dsh-context (20).
      { name: 'conversation.view', id: 'request-log', order: 30, locale: NS, label: () => t('tab') },
      props => h(RequestLogView, props),
    )
  })
}

// Named exports (the CJS bundle delivers them as module.exports members —
// the shape the harness's client module loader consumes).
export const name = 'dsh-request-log'
export const inject = ['slots', 'locale']
export { apply }
